# Generated by Django 4.0.3 on 2022-03-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0002_alter_client_latitude_alter_client_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='reporter',
            new_name='client',
        ),
    ]
