# Generated by Django 4.0.3 on 2022-03-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_rename_reporter_destination_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='created_at',
            new_name='date',
        ),
    ]
